ALTER TABLE `BIDS` MODIFY COLUMN `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `Bids` ADD COLUMN `PlayerCommunications` TEXT;
ALTER TABLE `Events` ADD COLUMN `PlayerCommunications` TEXT;